Run tests with pip constraints on Sundays in CI
psycopg/psycopg pull request #209
Opened 2022-01-16 15:49 UTC by dlax

We add a scheduled job in github actions at 18:19 UTC, on Sunday that
will run tests with pip constraints.

2022-01-16 16:52 UTC, dvarrazzo requested changes
Hi @dlax, thank you for this.

I was thinking to do it as well, but it wasn't immediately obvious for me how to do it. I am not sure that setting the env in a step also sets it in other step, I would honestly be surprised if it did. Did you try it? [Docs only mention](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsenv)  that a more specific env overrides a more generic.

The right place to set that env var - if I had defined the github action syntax myself - would be the `schedule` entry, but that [doesn't seem supported](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onschedule).

Another thing that would have been great would have been to define the wrokflow in a file to import from other files, overriding the env vars to customize different runs. Pretty easy to do in GitLab but it doesn't seem possible in Github either... Or maybe no, that's not true: I see [reusable workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows). Maybe those could work better?

Having this lower bound checked periodically is useful, but less critical than the upper bound. So, if we can schedule it easily, that's ok for me, but if it's not easily possible I would be ok to leave it in a floating branch to rebase periodically.

2022-01-16 16:52 UTC, dvarrazzo commented on .github/workflows/tests.yml
> +          PIP_CONSTRAINT: ${{ github.workspace }}/tests/constraints.txt
Are you sure that an env set in a step affects the other steps? I doubt it does, I would think they are isolated

2022-01-16 16:52 UTC, dvarrazzo commented on .github/workflows/tests.yml
> +    - cron: '19 18 * * 0'
If we do this we should change the postgis version of Python to 3.8, as explained in the floating commit to check the minimum version so far: the shapely version 1.7.0 specified as minimum requirements has only binary packages up to 3.8. Other Python versions require Shapely to be installed from source, but this requires the libgeos-dev library installed.

2022-01-16 16:52 UTC, dvarrazzo commented on .github/workflows/tests.yml
> +        if: github.event.schedule == '19 18 * * 0'
This is clever, although brittle :smile:

2022-01-16 18:32 UTC, dlax commented
> I was thinking to do it as well, but it wasn't immediately obvious for me how to do it. I am not sure that setting the env in a step also sets it in other step, I would honestly be surprised if it did. Did you try it? [Docs only mention](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsenv) that a more specific env overrides a more generic.

I tried it and thought it was working but now double-checking it actually does not. (I got trapped by the fact that most dependencies in the constraints file were already the latest -- only pytest-randomly has a newer version.)



> Having this lower bound checked periodically is useful, but less critical than the upper bound. So, if we can schedule it easily, that's ok for me, but if it's not easily possible I would be ok to leave it in a floating branch to rebase periodically.

I see; makes sense.

I'll think a bit more about this later on this week and, if no solution appears, I agree, we can live with that.

2022-01-24 14:27 UTC, dlax commented
All things considered, I'm withdrawing this.

2022-01-24 14:27 UTC, closed without merging