Use a static notification function for PQsetNoticeReceiver. Fixes #300
psycopg/psycopg pull request #360
Opened 2022-08-27 15:37 UTC by apollo13

The connection is passed via the optional *arg.

2022-08-27 20:15 UTC, dvarrazzo requested changes
I have tried faffing a bit with the ctypes object and haven't found a more streamlined way to do what you are doing now, so I think we are ok with this.

2022-08-27 20:15 UTC, dvarrazzo commented on psycopg/psycopg/pq/pq_ctypes.py
> +        # Keep alive for the duration of PGconn
```suggestion
        # Keep alive for the lifetime of PGconn
```

2022-08-27 20:15 UTC, dvarrazzo commented on psycopg/psycopg/pq/pq_ctypes.py
> +        "_py_object_helper",
Maybe another name? `_self_ptr`?

2022-08-28 07:14 UTC, apollo13 commented
I had to adjust the test a bit to use async functions because otherwise `poll.map` simply won't finish if the subprocess crashes (keeps waiting for results). The timeout of 10 seconds is rather long but should only be an issue if the error condition is triggered, so it should not happen. I verified that the test breaks when my changes are not applied.

2022-08-28 08:37 UTC, apollo13 commented
Ok, now I am confused. I'd expect the mac/windows tests to fail consistently if they cannot pickle `__main__.test`. Why do they sometimes work and sometimes not? Also this test only makes sense when multiprocessing uses fork a method, should we just adjust it to skip other systems?

2022-08-28 10:10 UTC, dvarrazzo approved these changes
Looks ok to me.

I've rebased your changes on the maint-3.0 branch and pushed to [run the tests](https://github.com/psycopg/psycopg/actions/runs/2942607003).

It occurred to me that you have worked on the master branch (to become 3.1), but the first tests you made were on a 3.0.x version. Could you please run a quick test on your system to verify that the changes applied work even on the [pgnotifyfixes-3.0 branch](https://github.com/psycopg/psycopg/tree/pgnotifyfixes-3.0)?

Thank you very much!

2022-08-28 10:22 UTC, apollo13 commented
I ran that single test against 3.0 and it worked fine. That said I get loads of failures in the async tests on 3.0:
```
FAILED tests/test_connection_async.py::test_auto_transaction - AttributeError: 'async_generator' object has no attribute 'pgconn'
FAILED tests/test_connection_async.py::test_autocommit_unknown - AttributeError: 'async_generator' object has no attribute 'close'
FAILED tests/test_connection_async.py::test_autocommit_inerror - AttributeError: 'async_generator' object has no attribute 'cursor'
FAILED tests/test_connection_async.py::test_transaction_param_default[isolation_level] - AttributeError: 'async_generator' object has no attribute 'isolation_level'
FAILED tests/test_connection_async.py::test_set_transaction_param_not_intrans_external[deferrable] - AttributeError: 'async_generator' object has no attribute 'set_autocommit'
FAILED tests/test_connection_async.py::test_execute_binary - AttributeError: 'async_generator' object has no attribute 'execute'
FAILED tests/test_connection_async.py::test_notice_handlers - AttributeError: 'async_generator' object has no attribute 'add_notice_handler'
FAILED tests/test_connection_async.py::test_cursor_factory - AttributeError: 'async_generator' object has no attribute 'cursor_factory'
FAILED tests/test_connection_async.py::test_set_transaction_param_block[isolation_level-True] - AttributeError: 'async_generator' object has no attribute 'set_autocommit'
FAILED tests/test_connection_async.py::test_transaction_param_default[deferrable] - AttributeError: 'async_generator' object has no attribute 'deferrable'
FAILED tests/test_connection_async.py::test_set_transaction_param_implicit[isolation_level-True] - AttributeError: 'async_generator' object has no attribute 'set_autocommit'
```
but those do happen even before my changes and are gone on 3.1. Not sure what is going on here.

2022-08-28 10:33 UTC, dvarrazzo commented
Do you mean that [these tests](https://github.com/psycopg/psycopg/runs/8056831752?check_suite_focus=true#step:8:41) fail for you?

Please note that tests in 3.0 and 3.1 use a different pytest-asyncio version: maybe the difference comes from there?

2022-08-28 11:02 UTC, apollo13 commented
> Do you mean that [these tests](https://github.com/psycopg/psycopg/runs/8056831752?check_suite_focus=true#step:8:41) fail for you?

Not just those but most tests including `_async.py` in their filename. That said I ran the new test manually and also ran the 3.0 branch against Django. Given that the tests work in CI (handlers are tested there after all) and the commit doesn't make things worse locally I am not going to inspect why the 3.0 testsuite doesn't work for me locally (although your pstest-asyncio might be the culprit).

2022-08-28 11:38 UTC, dvarrazzo commented
That's ok: your changes here are an improvement and I'm happy to merge them. If there is any fallout from them, we will deal with it afterwards.

By the way, [the Cython implementation](https://github.com/psycopg/psycopg/blob/c4c3fbee0258ddaae08c4f54502c66be2a9692fc/psycopg_c/psycopg_c/pq/pgconn.pyx#L41) is pretty similar what you have done here. I think that was my original intention, but I couldn't get to the bottom of it because my knowledge of ctypes was much poorer. So, I'm happy about this your implementation, thank you.

I'll force-pushing my changes here (I reworded the commit message and added a news entry) and merging to master too.

2022-08-28 12:03 UTC, merged