Allow binary JSON dumps
psycopg/psycopg pull request #568
Opened 2023-05-19 12:08 UTC by lionel-panhaleux

Some JSON libraries, in particular the widespread [orjson](https://github.com/ijl/orjson#quickstart) library, directly dump data in binary format.

This change allows it and avoids having to decode/encode in these cases by testing the return type of the `dumps` function.

2023-05-19 17:06 UTC, lionel-panhaleux commented
Of course @dlax, thanks for pointing out the right place to add the test. Here it is: I hope that fits ☺︎

2023-05-19 18:18 UTC, dvarrazzo requested changes
Hello @lionel-panhaleux 

thank you very much, this seems useful indeed!

Could you please add a release note in `docs/news.rst`? Something of the tone of "make JSON dumper compatible with JSON libraries dumping as bytes (such as orjson)"

...sure they should have called the function `dumpb()`... :thinking:

2023-05-20 09:08 UTC, pauloxnet commented
Interesting.
I think it can be useful for also for `msgspec` which _"decodes and validates JSON ~2x faster than orjson can decode it alone."_.
https://github.com/jcrist/msgspec

2023-05-26 13:08 UTC, lionel-panhaleux commented on tests/types/test_json.py
> +    set_json_dumps(my_dumps_bytes)
Done

2023-05-26 13:08 UTC, lionel-panhaleux commented
> 

Done

2023-05-26 13:57 UTC, dvarrazzo commented
Thank you very much, looks good!

2023-06-04 22:29 UTC, merged

2023-06-04 22:29 UTC, dvarrazzo commented
Merged! Thank you very much for your contribution!

2023-07-31 23:49 UTC, aaron11496 commented
@dvarrazzo This is in the [release notes for 3.1.9](https://www.psycopg.org/psycopg3/docs/news.html#psycopg-3-1-9) but I don't think it's actually in 3.1.9 since it was merged June 4 and [3.1.9](https://github.com/psycopg/psycopg/releases/tag/3.1.9) is tagged May 2. Am I reading this right?

I discovered this while attempting to use orjson with Psycopg and found that it didn't work with 3.1.9 but looks like it would work on [current master](https://github.com/psycopg/psycopg/blob/47bea5a87b5283468b46e4421a145d0487ccf104/psycopg/psycopg/types/json.py#L135-L138).

2023-08-01 10:07 UTC, dvarrazzo commented
Oops, I believe you are right, @aaron11496 :sweat_smile: It's a mistake in the news file.

I also thought it was already released... I will release 3.1.10 soon with this change too.

2023-08-05 14:26 UTC, dvarrazzo commented
FYI, psycopg 3.1.10 has been released, including this MR too. Sorry about the delay, happy hacking!