add a 'size' parameter to Cursor.stream()
psycopg/psycopg pull request #794
Opened 2024-04-17 10:22 UTC by dlax

Based on #793

2024-04-17 20:38 UTC, dvarrazzo commented on docs/api/cursors.rst
> +            This `size` parameter is only available from libpq 17, you can use
```suggestion
            This `size` parameter is only available from libpq 17, you can use the
```

2024-04-17 21:00 UTC, dvarrazzo commented
Heads up: I gave a forced push to the branch because github didn't detect that #793 was merged and the MR still showed two commits.

2024-04-17 21:04 UTC, dvarrazzo requested changes
Just some nits, but otherwise looks good, thank you :slightly_smiling_face:

2024-04-17 21:04 UTC, dvarrazzo commented on psycopg/psycopg/cursor_async.py
> +                    # a chunk of rows.
I think we can drop this comment altogether. The previous one was about assumption about there being exactly one record, but here we are making a careful iteration on >= 0 records.
```suggestion
```

2024-04-17 21:04 UTC, dvarrazzo commented on docs/api/cursors.rst
> +            This `size` parameter is only available from libpq 17, you can use
```suggestion
            This `size` parameter is only available from libpq 17, you can use the
```

2024-04-19 07:04 UTC, dlax commented on psycopg/psycopg/_cursor_base.py
> +        if status in (SINGLE_TUPLE, TUPLES_CHUNK):
I didn't know that; thank you for sharing.

Fixed, along with other suggestions.

2024-06-12 17:27 UTC, dvarrazzo commented
I've rebased this to master and about to merge it.

2024-06-13 14:06 UTC, merged