build: avoid installing tomli on recent python
psycopg/psycopg pull request #846
Opened 2024-06-26 03:23 UTC by eli-schwartz

It is in the stdlib. No need to have wheel building require downloading yet another build dependency.

2024-06-26 06:11 UTC, dlax approved these changes

2024-06-26 09:02 UTC, dvarrazzo requested changes

2024-06-26 09:02 UTC, dvarrazzo commented on psycopg_c/pyproject.toml
> +requires = ["setuptools >= 49.2.0", "wheel >= 0.37", "tomli >= 2.0.1 ; python_version<'3.11'"]
Thank you! Can you please split this list on multiple lines?

```suggestion
requires = [
    "setuptools >= 49.2.0",
    "wheel >= 0.37",
    "tomli >= 2.0.1 ; python_version<'3.11'",
]
```

2024-06-28 16:37 UTC, dvarrazzo approved these changes

2024-06-28 16:37 UTC, merged

2024-06-28 16:38 UTC, dvarrazzo commented
I have applied the lint change myself and merged. Thank you very much!

2024-06-28 16:38 UTC, eli-schwartz commented
Thanks, and sorry -- I meant to do that earlier but forgot.